[tools]
bun = '1'
uv = 'latest'

[settings]
status.show_env = true
status.show_tools = true
legacy_version_file = true

[[env]]
_.file = '.env'
_.python.venv = { path = ".venv" }
DEBUG = 'eslint:eslint'
# [[env]]
# _.file = '.env.local'
