'use client';

import '@mantine/code-highlight/styles.css';
import {
  ActionIcon,
  Button,
  Group,
  TextInput,
  Textarea,
  Title,
  Tooltip,
} from '@mantine/core';
import { useForm } from '@mantine/form';
import { useCallback, useState } from 'react';
import { BiWallet } from 'react-icons/bi';
import { isAddress, isHex, verifyMessage } from 'viem';
import { useAccount } from 'wagmi';

export const VerifyMessage: React.FC = () => {
  const form = useForm({
    initialValues: {
      address: '',
      message: '',
      signature: '',
    },
    validate: {
      address: (value) => (isAddress(value) ? null : 'Invalid address'),
      signature: (value) => (isHex(value) ? null : 'Invalid signature'),
    },
  });

  const { address } = useAccount();
  const fillAddressFromWallet = useCallback(() => {
    form.setFieldValue('address', address as string);
  }, [form, address]);

  const [result, setResult] = useState<boolean | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  return (
    <form
      onSubmit={form.onSubmit(async (values) => {
        setResult(null);
        setIsLoading(true);
        await new Promise((resolve) => setTimeout(resolve, 1000));
        try {
          const result = await verifyMessage({
            address: values.address as `0x${string}`,
            message: values.message,
            signature: values.signature as `0x${string}`,
          });
          setResult(result);
        } catch (error) {
          form.setFieldError('signature', (error as Error).message);
          setResult(false);
        }
        setIsLoading(false);
      })}
    >
      <Title my='lg'>Verify a message</Title>
      <TextInput
        label='Address'
        description='The Ethereum address that signed the original message.'
        placeholder='Type an address here.'
        disabled={isLoading}
        rightSection={
          <Tooltip label='Use current wallet address'>
            <ActionIcon
              variant='subtle'
              aria-label='Use current wallet address'
              onClick={fillAddressFromWallet}
              disabled={!address}
            >
              <BiWallet />
            </ActionIcon>
          </Tooltip>
        }
        {...form.getInputProps('address')}
      />
      <Textarea
        label='Message'
        description='The message to be verified.'
        placeholder='Type a message here.'
        disabled={isLoading}
        {...form.getInputProps('message')}
      />
      <Textarea
        label='Signature'
        description="The signature that was generated by signing the message with the address's private key."
        placeholder='Type a signature here.'
        disabled={isLoading}
        {...form.getInputProps('signature')}
      />
      <Group>
        <Button miw={124} mt='lg' type='submit' loading={isLoading}>
          Verify
        </Button>
        {result !== null && (
          <Title mt='lg' size='sm'>
            {result ? '✅' : '❌'} {result ? 'Valid' : 'Invalid'}
          </Title>
        )}
      </Group>
    </form>
  );
};
